name: GitHub Actions Demo
run-name: GitHub Actions Demo

# 觸發此 action 的時機
on:
  push:
    branchs:  # 只要有任何一個 commit 被 push，就會觸發此 action
      '*'
  workflow_dispatch:  # 可以手動執行此 action

# 預先定義此 action 要幹嘛
jobs:
  demo:
    runs-on: ubuntu-latest # 使用 ubuntu-latest 作為 runner
    steps:
      run:
        echo "Hello, world 1!"
        echo "Hello, world 2!"